interface CommandInfo {
    desc: string;
}

export const COMMANDS: Record<string, CommandInfo> = {
    'check':                { desc: 'Check a checkbox' },
    'clear':                { desc: 'Clear the console' },
    'click':                { desc: 'Click an element' },
    'config-print':         { desc: 'Print config' },
    'console':              { desc: 'Console messages' },
    'cookie-clear':         { desc: 'Clear cookies' },
    'cookie-delete':        { desc: 'Delete cookie' },
    'cookie-get':           { desc: 'Get cookie' },
    'cookie-list':          { desc: 'List cookies' },
    'cookie-set':           { desc: 'Set cookie' },
    'dblclick':             { desc: 'Double-click' },
    'dialog-accept':        { desc: 'Accept dialog' },
    'dialog-dismiss':       { desc: 'Dismiss dialog' },
    'drag':                 { desc: 'Drag and drop' },
    'eval':                 { desc: 'Evaluate JavaScript' },
    'export':               { desc: 'Export as Playwright test' },
    'fill':                 { desc: 'Fill a form field' },
    'go-back':              { desc: 'Go back' },
    'go-forward':           { desc: 'Go forward' },
    'goto':                 { desc: 'Navigate to a URL' },
    'help':                 { desc: 'Show available commands' },
    'history':              { desc: 'Show command history' },
    'history clear':        { desc: 'Clear command history' },
    'hover':                { desc: 'Hover over element' },
    'localstorage-clear':   { desc: 'Clear localStorage' },
    'localstorage-delete':  { desc: 'Delete localStorage' },
    'localstorage-get':     { desc: 'Get localStorage' },
    'localstorage-list':    { desc: 'List localStorage' },
    'localstorage-set':     { desc: 'Set localStorage' },
    'network':              { desc: 'Network requests' },
    'open':                 { desc: 'Open the browser' },
    'pdf':                  { desc: 'Save as PDF' },
    'press':                { desc: 'Press a keyboard key' },
    'reload':               { desc: 'Reload page' },
    'resize':               { desc: 'Resize window' },
    'route':                { desc: 'Add network route' },
    'route-list':           { desc: 'List routes' },
    'run-code':             { desc: 'Run Playwright code' },
    'screenshot':           { desc: 'Take a screenshot' },
    'select':               { desc: 'Select dropdown option' },
    'sessionstorage-clear': { desc: 'Clear sessionStorage' },
    'sessionstorage-delete':{ desc: 'Delete sessionStorage' },
    'sessionstorage-get':   { desc: 'Get sessionStorage' },
    'sessionstorage-list':  { desc: 'List sessionStorage' },
    'sessionstorage-set':   { desc: 'Set sessionStorage' },
    'snapshot':             { desc: 'Accessibility snapshot' },
    'state-load':           { desc: 'Load storage state' },
    'state-save':           { desc: 'Save storage state' },
    'tab-close':            { desc: 'Close tab' },
    'tab-list':             { desc: 'List tabs' },
    'tab-new':              { desc: 'New tab' },
    'tab-select':           { desc: 'Select tab' },
    'type':                 { desc: 'Type text key by key' },
    'uncheck':              { desc: 'Uncheck a checkbox' },
    'unroute':              { desc: 'Remove route' },
    'upload':               { desc: 'Upload a file' },
    'verify':               { desc: 'Assert page state (title, url, text, element, value, list)' },
    'verify-element':       { desc: 'Verify element exists' },
    'verify-no-element':    { desc: 'Verify element not exists' },
    'verify-no-text':       { desc: 'Verify text not visible' },
    'verify-text':          { desc: 'Verify text visible' },
    'verify-title':         { desc: 'Verify page title' },
    'verify-url':           { desc: 'Verify page URL' },
};

// Aliases from parser.ts (core package not available in extension bundle)
export const ALIASES = [
  'o', 'g', 'go', 'back', 'fwd', 'r',
  'c', 'dc', 't', 'f', 'h', 'p', 'sel', 'chk', 'unchk',
  'hl', 's', 'snap', 'ss', 'e', 'con', 'net',
  'tl', 'tn', 'tc', 'ts',
  'v', 'vt', 've', 'vv', 'vl',
  'q', 'ls',
];

export const COMMAND_NAMES = Object.keys(COMMANDS);
